import type { DB } from "./types";

// Real profile data from Royce's vertical profile.
export const seed: DB = {
  profile: {
    name: "Royce",
    alias: "Chris",
    base: "France",
    born: 1987,
    languages: ["French", "English", "Korean (B1)", "Mandarin", "Japanese"],
    nonprofitTargetPct: 15,
    energyCommittedPct: 72,
  },
  goals: [
    {
      id: "g-kpop",
      title: "Break into the K-pop industry",
      vertical: "K-pop",
      progress: 45,
      target: "Land a co-write or session credit with a Korean label",
      timeframe: "2026",
      milestones: [
        { id: "g-kpop-m1", label: "B1 Korean conversational", done: true },
        { id: "g-kpop-m2", label: "Build 3 label contacts (1theK, HYBE, SM)", done: true },
        { id: "g-kpop-m3", label: "Release 1 K-pop style arrangement cover", done: true },
        { id: "g-kpop-m4", label: "Secure a Seoul writing session", done: false },
        { id: "g-kpop-m5", label: "Co-write credit on a release", done: false },
      ],
    },
    {
      id: "g-hnwi",
      title: "Grow HNWI private-event circuit",
      vertical: "Music",
      progress: 68,
      target: "€40K/yr from Switzerland & Monaco private events",
      timeframe: "2026",
      milestones: [
        { id: "g-hnwi-m1", label: "Geneva promoter relationship (Sophie)", done: true },
        { id: "g-hnwi-m2", label: "Monaco gala booking", done: true },
        { id: "g-hnwi-m3", label: "3 referral clients from gala", done: false },
      ],
    },
    {
      id: "g-nonprofit",
      title: "Redistribute 15% to SEA / marginalized communities",
      vertical: "Nonprofit",
      progress: 12,
      target: "15% of annual revenue redistributed",
      timeframe: "Ongoing",
      milestones: [
        { id: "g-np-m1", label: "Register giving structure", done: true },
        { id: "g-np-m2", label: "Pick 3 partner causes", done: true },
        { id: "g-np-m3", label: "Reach 15% of YTD", done: false },
      ],
    },
    {
      id: "g-content",
      title: "Scale integrated content channel",
      vertical: "Content",
      progress: 38,
      target: "50K subscribers across travel + piano",
      timeframe: "2026",
      milestones: [
        { id: "g-c-m1", label: "Weekly posting cadence", done: true },
        { id: "g-c-m2", label: "Launch integrated travel+piano series", done: false },
        { id: "g-c-m3", label: "First brand-sponsored series", done: false },
      ],
    },
  ],
  countries: [
    {
      id: "c-kr",
      name: "South Korea",
      flag: "🇰🇷",
      status: "Active",
      notes: "Highest music-industry upside. Most active market — €22K generated.",
      roadmap: [
        { id: "kr-r1", label: "Maintain 1theK relationship (David Kim)", done: true },
        { id: "kr-r2", label: "Re-warm Min-jae Park (producer)", done: false },
        { id: "kr-r3", label: "Seoul Arts Council grant", done: false },
        { id: "kr-r4", label: "Book a Seoul writing residency", done: false },
      ],
    },
    {
      id: "c-ch",
      name: "Switzerland",
      flag: "🇨🇭",
      status: "Active",
      notes: "HNWI private events. Top revenue country — €31K.",
      roadmap: [
        { id: "ch-r1", label: "Geneva promoter (Sophie Chen)", done: true },
        { id: "ch-r2", label: "Build referral pipeline", done: false },
      ],
    },
    {
      id: "c-mc",
      name: "Monaco",
      flag: "🇲🇨",
      status: "Active",
      notes: "Gala circuit, ultra-HNWI. Linked with Switzerland leg.",
      roadmap: [
        { id: "mc-r1", label: "Gala performance booked", done: true },
        { id: "mc-r2", label: "Convert gala into 3 private bookings", done: false },
      ],
    },
    {
      id: "c-jp",
      name: "Japan",
      flag: "🇯🇵",
      status: "Building",
      notes: "J-pop crossover + residency potential (Villa Kujoyama, Sasakawa).",
      roadmap: [
        { id: "jp-r1", label: "Akira Tanaka (Tokyo J-pop) intro", done: true },
        { id: "jp-r2", label: "Villa Kujoyama residency app", done: false },
        { id: "jp-r3", label: "Tokyo session week", done: false },
      ],
    },
    {
      id: "c-us",
      name: "USA",
      flag: "🇺🇸",
      status: "Exploring",
      notes: "Content audience base; brand deals.",
      roadmap: [{ id: "us-r1", label: "Identify 2 brand partners", done: false }],
    },
    {
      id: "c-tw",
      name: "Taiwan",
      flag: "🇹🇼",
      status: "Exploring",
      notes: "Best near-term opportunity density per euro.",
      roadmap: [{ id: "tw-r1", label: "Scout Taipei venues", done: false }],
    },
    {
      id: "c-hk",
      name: "Hong Kong",
      flag: "🇭🇰",
      status: "Exploring",
      notes: "Finance-sector private events.",
      roadmap: [{ id: "hk-r1", label: "1 HNWI intro", done: false }],
    },
  ],
  grants: [
    {
      id: "gr-seoul",
      name: "Seoul Arts Council",
      country: "South Korea",
      flag: "🇰🇷",
      type: "K-pop crossover",
      stage: "Submitted",
      amount: 15000,
      due: "2026-06-12",
      notes: "Strongest cultural-exchange angle. Reuse Japan exchange essay.",
      checklist: [
        { id: "gr-seoul-c1", label: "Project narrative", done: true },
        { id: "gr-seoul-c2", label: "Budget sheet", done: true },
        { id: "gr-seoul-c3", label: "2 letters of support", done: true },
        { id: "gr-seoul-c4", label: "Korean translation", done: false },
        { id: "gr-seoul-c5", label: "Submit portal", done: false },
      ],
    },
    {
      id: "gr-kujoyama",
      name: "Villa Kujoyama",
      country: "Japan",
      flag: "🇯🇵",
      type: "Kyoto residency",
      stage: "Preparing",
      amount: 20000,
      due: "2026-07-30",
      notes: "Statement 80% done.",
      checklist: [
        { id: "gr-k-c1", label: "Artist statement", done: true },
        { id: "gr-k-c2", label: "Portfolio reel", done: true },
        { id: "gr-k-c3", label: "Reference letters", done: false },
      ],
    },
    {
      id: "gr-sasakawa",
      name: "Sasakawa Foundation",
      country: "Japan",
      flag: "🇯🇵",
      type: "Japan exchange",
      stage: "Awarded",
      amount: 22000,
      due: "",
      notes: "Won. Reporting due Q4.",
      checklist: [
        { id: "gr-s-c1", label: "Acceptance signed", done: true },
        { id: "gr-s-c2", label: "Mid-term report", done: false },
      ],
    },
    {
      id: "gr-acc",
      name: "Asian Cultural Council",
      country: "South Korea",
      flag: "🌏",
      type: "Tourism / crossover",
      stage: "Research",
      amount: 25000,
      due: "2026-09-15",
      notes: "Fit check in progress.",
      checklist: [{ id: "gr-acc-c1", label: "Eligibility check", done: false }],
    },
    {
      id: "gr-nordic",
      name: "Nordic Culture Fund",
      country: "Sweden",
      flag: "🇸🇪",
      type: "Collaboration",
      stage: "Submitted",
      amount: 14000,
      due: "2026-06-30",
      notes: "Awaiting decision.",
      checklist: [{ id: "gr-n-c1", label: "Submitted", done: true }],
    },
    {
      id: "gr-spedidam",
      name: "SPEDIDAM Tour Aid",
      country: "France",
      flag: "🇫🇷",
      type: "12-city tour",
      stage: "Awarded",
      amount: 16000,
      due: "",
      notes: "Won. Funds touring leg.",
      checklist: [{ id: "gr-sp-c1", label: "Accepted", done: true }],
    },
  ],
  contacts: [
    {
      id: "ct-minjae",
      name: "Min-jae Park",
      role: "Producer",
      country: "South Korea",
      flag: "🇰🇷",
      warmth: "Cool",
      lastContact: "2026-03-28",
      tags: ["K-pop", "Producer", "Seoul"],
      nextAction: "Send the new K-pop arrangement demo to re-warm",
      history: [
        { id: "ct-mj-h1", date: "2026-03-28", note: "Replied politely, busy season." },
        { id: "ct-mj-h2", date: "2026-01-15", note: "Coffee in Seoul, discussed co-write." },
        { id: "ct-mj-h3", date: "2025-11-02", note: "Intro via David Kim." },
      ],
    },
    {
      id: "ct-david",
      name: "David Kim",
      role: "A&R, 1theK",
      country: "South Korea",
      flag: "🇰🇷",
      warmth: "Active",
      lastContact: "2026-06-02",
      tags: ["K-pop", "Label", "1theK"],
      nextAction: "Share Seoul residency timeline",
      history: [
        { id: "ct-dk-h1", date: "2026-06-02", note: "Call: open to a writing session in fall." },
        { id: "ct-dk-h2", date: "2026-04-20", note: "Liked the cover; shared internally." },
      ],
    },
    {
      id: "ct-sophie",
      name: "Sophie Chen",
      role: "Promoter",
      country: "Switzerland",
      flag: "🇨🇭",
      warmth: "Active",
      lastContact: "2026-05-30",
      tags: ["HNWI", "Geneva", "Events"],
      nextAction: "Confirm two autumn private events",
      history: [
        { id: "ct-sc-h1", date: "2026-05-30", note: "Pitched autumn salon series." },
        { id: "ct-sc-h2", date: "2026-03-10", note: "Monaco gala referral." },
      ],
    },
    {
      id: "ct-akira",
      name: "Akira Tanaka",
      role: "J-pop A&R",
      country: "Japan",
      flag: "🇯🇵",
      warmth: "Warm",
      lastContact: "2026-05-10",
      tags: ["J-pop", "Tokyo", "Label"],
      nextAction: "Propose Tokyo session week dates",
      history: [
        { id: "ct-ak-h1", date: "2026-05-10", note: "Positive on crossover idea." },
      ],
    },
  ],
  income: [
    { id: "in-1", label: "Monaco gala performance", stream: "HNWI / Private", country: "Monaco", flag: "🇲🇨", amount: 9500, date: "2026-06-04" },
    { id: "in-2", label: "Geneva private salon", stream: "HNWI / Private", country: "Switzerland", flag: "🇨🇭", amount: 6800, date: "2026-05-18" },
    { id: "in-3", label: "Seoul brand campaign", stream: "Brand deals", country: "South Korea", flag: "🇰🇷", amount: 7200, date: "2026-05-22" },
    { id: "in-4", label: "Spring concert series", stream: "Concerts", country: "France", flag: "🇫🇷", amount: 5400, date: "2026-04-12" },
    { id: "in-5", label: "Online piano school", stream: "Online school / shop", country: "Global", flag: "🌍", amount: 4100, date: "2026-05-01" },
    { id: "in-6", label: "Private teaching block", stream: "Teaching", country: "France", flag: "🇫🇷", amount: 3600, date: "2026-05-05" },
    { id: "in-7", label: "Sasakawa residency grant", stream: "Grants / residencies", country: "Japan", flag: "🇯🇵", amount: 22000, date: "2026-02-20" },
    { id: "in-8", label: "Tokyo crossover session", stream: "Concerts", country: "Japan", flag: "🇯🇵", amount: 2940, date: "2026-03-15" },
  ],
  bookings: [
    { id: "bk-monaco", title: "Monaco Charity Gala", type: "HNWI / Private", city: "Monaco", country: "Monaco", flag: "🇲🇨", date: "2026-06-04", fee: 9500, status: "Completed", notes: "Black tie, 45-min set, grand piano provided." },
    { id: "bk-geneva", title: "Geneva Autumn Salon", type: "HNWI / Private", city: "Geneva", country: "Switzerland", flag: "🇨🇭", date: "2026-10-09", fee: 7000, status: "Confirmed", notes: "Sophie Chen — intimate salon." },
    { id: "bk-seoul", title: "Seoul Writing Session", type: "Session", city: "Seoul", country: "South Korea", flag: "🇰🇷", date: "2026-09-20", fee: 0, status: "Holding", notes: "With 1theK (David Kim). Fee TBD / credit-based." },
    { id: "bk-paris", title: "Paris Recital", type: "Classical", city: "Paris", country: "France", flag: "🇫🇷", date: "2026-07-02", fee: 2800, status: "Confirmed", notes: "Part of SPEDIDAM-funded tour." },
    { id: "bk-tokyo", title: "Tokyo Crossover Night", type: "K-pop", city: "Tokyo", country: "Japan", flag: "🇯🇵", date: "2026-09-25", fee: 3200, status: "Inquiry", notes: "Akira Tanaka — tie to Seoul leg." },
  ],
  content: [
    { id: "co-1", title: "Seoul vlog — label meetings", channel: "Travel", status: "Editing", date: "2026-06-10", notes: "Pair with piano cover." },
    { id: "co-2", title: "Spring Day (BTS) piano arr.", channel: "Piano", status: "Published", date: "2026-06-02", notes: "Drives shop sales." },
    { id: "co-3", title: "Monaco gala behind-the-scenes", channel: "Integrated", status: "Filming", date: "2026-06-12", notes: "HNWI angle." },
    { id: "co-4", title: "60s: practice with me", channel: "Shorts", status: "Idea", date: "2026-06-14", notes: "Repurpose from vlog." },
    { id: "co-5", title: "Kyoto residency teaser", channel: "Travel", status: "Scripted", date: "2026-06-20", notes: "Conditional on grant." },
  ],
  arrangements: [
    { id: "ar-springday", title: "Spring Day", artist: "BTS", category: "K-pop", difficulty: "Intermediate", inShop: true, price: 9, usedInSetlists: 4 },
    { id: "ar-river", title: "River Flows in You", artist: "Yiruma", category: "Contemporary", difficulty: "Intermediate", inShop: true, price: 7, usedInSetlists: 9 },
    { id: "ar-clair", title: "Clair de Lune", artist: "Debussy", category: "Classical", difficulty: "Advanced", inShop: true, price: 12, usedInSetlists: 11 },
    { id: "ar-dynamite", title: "Dynamite", artist: "BTS", category: "K-pop", difficulty: "Easy", inShop: true, price: 6, usedInSetlists: 3 },
    { id: "ar-nocturne", title: "Nocturne Op.9 No.2", artist: "Chopin", category: "Classical", difficulty: "Advanced", inShop: false, price: 0, usedInSetlists: 7 },
    { id: "ar-through", title: "Through the Night", artist: "IU", category: "K-pop", difficulty: "Intermediate", inShop: true, price: 8, usedInSetlists: 2 },
  ],
  contributions: [
    { id: "cn-1", cause: "SEA music education fund", region: "Vietnam", amount: 600, date: "2026-03-01" },
    { id: "cn-2", cause: "Marginalized youth scholarship", region: "Thailand", amount: 450, date: "2026-04-15" },
    { id: "cn-3", cause: "Community arts space", region: "Philippines", amount: 300, date: "2026-05-20" },
  ],
};
